apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference-probes
spec:
  containers:
    - image: stepdan23/online_inference:v2
      name: online-inference

      ports:
        - name: app-port
          containerPort: 8000
          hostPort: 8000

      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"

      livenessProbe:
        httpGet:
          path: /health
          port: app-port
        failureThreshold: 2
        periodSeconds: 10

      startupProbe:
        httpGet:
          path: /health
          port: app-port
        failureThreshold: 5
        periodSeconds: 5