logger_config_path: "configs/logger.yml"
input_data_path: "data/heart.csv"
test_data_path: "data/heart.csv"
predict_path: "models/predicts.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"

split_params:
  val_size: 0.1
  random_state: 23

train_params:
  model_type: "LogisticRegression"
  params:
    random_state: 23

feature_params:
  cat_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  num_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  transform_params:
    - trans_name: "imputer"
      trans_class: "SimpleImputer"
      column_names:
        - "age"
        - "trestbps"
        - "chol"
        - "thalach"
        - "oldpeak"
      params:
        strategy: "mean"
  target_col: "target"
