name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./ml_project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Pylint
        working-directory: ./ml_project
        run: |
          pylint src train.py  --ignore=tests --disable=C0114,C0115,C0116 --fail-under=7.0
