name: pylint_my_project

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ homework1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./ml_project
        run: |
          pip install .

      - name: Pylint
        working-directory: ./ml_project
        run: |
          pylint ml_project --disable=C0114,C0115,C0116 --fail-under=7.0
