name: test_ml_project

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ homework1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./ml_project
        run: |
          pip install .

      - name: Testing
        working-directory: ./ml_project
        run: |
          pytest -v .
